
# Overrride file for smaller batches and bigger window 9/6/2025

window: 5000000
token_persist_files: 70

# Smaller batch than we'd been using
# 20,000 is 40 seconds of the decahose (wall clock time) but only four seconds 
# of the firehose.
batch: 20000 

